In [67]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,roc_auc_score,classification_report,recall_score,precision_score
from sklearn.svm import SVC
import numpy as np
from sklearn.model_selection import KFold
from utils.eval import get_results
import json
from monai.networks.nets import DenseNet121
import torch
from monai.data import DataLoader, ImageDataset
from monai.transforms import RandRotate90, Resize, EnsureChannelFirst, Compose, ScaleIntensity,RandAxisFlip
import os
from tqdm import tqdm

Load Random forest model 

In [14]:
# Get features
features_2d = pd.read_csv('./Data/2D_t2/all.csv')
data = features_2d.drop(columns=['Center'])
correlation = data.iloc[:,2:].corr(method='spearman')
selected_features = correlation[(correlation.abs() <= 0.6) | (correlation.abs() == 1)]
for i in range(200):
    for index in range(selected_features.shape[0]):
        row = selected_features.iloc[index]
        to_drop = row[row.isna()].index
        selected_features_c_droped = selected_features.drop(labels=to_drop,axis=0)
        selected_features_r_droped = selected_features_c_droped.drop(labels=to_drop,axis=1)
        if selected_features_r_droped.shape[0]<selected_features.shape[0]:
            break
    selected_features = selected_features_r_droped
selected_data = data[selected_features.index.to_list()+['Label','Name']]

Organize label

In [ ]:
selected_data['Label'] = selected_data['Label'].apply(lambda x: x-1)

Read data

In [44]:
with open("Fold_data.json", "r") as file:
    fold_data = json.load(file)
train_list = fold_data['Fold1']['train']
test_list = fold_data['Fold1']['test']
train_data = selected_data[selected_data["Name"].isin(train_list)]
test_data = selected_data[selected_data["Name"].isin(test_list)]

Load DenseNet121

In [59]:
test_label_and_path = test_data[['Name','Label']]
test_label_and_path['Name'] = test_label_and_path['Name'].apply(lambda x: x + '.nii.gz')

C:\Users\sugar\AppData\Local\Temp\ipykernel_18656\1218906158.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_label_and_path['Name'] = test_label_and_path['Name'].apply(lambda x: x + '.nii.gz')


In [89]:
model = DenseNet121(
        spatial_dims=3,  # 3D input
        in_channels=1,   # Typically for grayscale (e.g., MRI/CT scans), change to 3 for RGB
        out_channels=2   # Adjust for binary or multi-class segmentation/classification
    )
model.load_state_dict(torch.load('./weights/fold1_best_auc_model.pth', map_location='cpu', weights_only=True))
model.to('cuda')
data_dir  = r"D:\DATASET\IPMN_t2_cyst\ROI"
test_transforms = Compose([ScaleIntensity(), EnsureChannelFirst(), Resize((96, 96, 96))])
test_ds = ImageDataset(image_files=[os.path.join(data_dir,name) for name in test_label_and_path['Name'].to_list()], labels=test_label_and_path['Label'].to_list(), transform=test_transforms)
test_dataloader = DataLoader(test_ds, batch_size=1, shuffle=False,num_workers=1)

In [ ]:

with torch.no_grad(): 
    progress_bar = tqdm(test_dataloader, desc="Testing")
    for X, y in progress_bar:
        X = X.to('cuda')
        pred = model(X)
        print(torch.nn.functional.softmax(pred, dim=-1).cpu().numpy())

Testing:   6%|▌         | 4/67 [00:04<00:52,  1.20it/s]

[[0.29357967 0.7064203 ]]
[[0.29043764 0.70956236]]
[[0.3034056  0.69659436]]
[[0.300858   0.69914204]]
[[0.29462793 0.7053721 ]]


Testing:  12%|█▏        | 8/67 [00:04<00:19,  3.09it/s]

[[0.29307303 0.70692694]]
[[0.2960248 0.7039752]]
[[0.29906562 0.70093435]]
[[0.28334036 0.7166596 ]]
[[0.29237732 0.7076227 ]]


Testing:  21%|██        | 14/67 [00:04<00:07,  7.26it/s]

[[0.29260185 0.7073981 ]]
[[0.2911219 0.7088781]]
[[0.29318857 0.70681137]]
[[0.2968329  0.70316714]]
[[0.2933376 0.7066624]]


Testing:  30%|██▉       | 20/67 [00:05<00:03, 11.76it/s]

[[0.29149216 0.70850784]]
[[0.29781982 0.70218015]]
[[0.311966 0.688034]]
[[0.2934325  0.70656747]]
[[0.30039307 0.69960696]]


Testing:  34%|███▍      | 23/67 [00:05<00:03, 14.00it/s]

[[0.30351582 0.6964842 ]]
[[0.29808295 0.70191705]]
[[0.30309978 0.6969002 ]]
[[0.29604957 0.70395046]]
[[0.2912838 0.7087162]]


Testing:  43%|████▎     | 29/67 [00:05<00:02, 16.87it/s]

[[0.29550207 0.7044979 ]]
[[0.28946972 0.7105303 ]]
[[0.28797895 0.71202105]]
[[0.29046866 0.7095313 ]]
[[0.2990722 0.7009278]]


Testing:  48%|████▊     | 32/67 [00:05<00:01, 17.88it/s]

[[0.29565832 0.7043417 ]]
[[0.2927567 0.7072433]]
[[0.2973358  0.70266426]]
[[0.28591236 0.7140876 ]]


Testing:  57%|█████▋    | 38/67 [00:05<00:01, 19.75it/s]

[[0.29477143 0.70522857]]
[[0.2923688 0.7076312]]
[[0.29414472 0.7058553 ]]
[[0.29433554 0.70566446]]
[[0.2927827  0.70721734]]


Testing:  66%|██████▌   | 44/67 [00:06<00:01, 20.93it/s]

[[0.28915197 0.71084803]]
[[0.29299253 0.70700747]]
[[0.3055187 0.6944813]]
[[0.3019181 0.6980819]]
[[0.2906806  0.70931935]]


Testing:  70%|███████   | 47/67 [00:06<00:00, 20.71it/s]

[[0.2860175  0.71398246]]
[[0.30540997 0.69459003]]
[[0.29091585 0.7090842 ]]
[[0.30200756 0.69799244]]
[[0.29541314 0.70458686]]


Testing:  79%|███████▉  | 53/67 [00:06<00:00, 20.92it/s]

[[0.28623986 0.71376014]]
[[0.29745683 0.7025432 ]]
[[0.2954802  0.70451987]]
[[0.28950426 0.71049577]]
[[0.29894903 0.70105094]]


Testing:  88%|████████▊ | 59/67 [00:06<00:00, 21.23it/s]

[[0.28702286 0.7129771 ]]
[[0.27896306 0.721037  ]]
[[0.29118833 0.7088117 ]]
[[0.2879287 0.7120713]]
[[0.29157567 0.7084243 ]]


Testing:  93%|█████████▎| 62/67 [00:07<00:00, 21.64it/s]

[[0.29100677 0.70899326]]
[[0.28858793 0.7114121 ]]
[[0.29630297 0.7036971 ]]
[[0.29112586 0.7088741 ]]
[[0.2891667 0.7108333]]


Testing:  97%|█████████▋| 65/67 [00:07<00:00, 21.71it/s]

[[0.29891288 0.7010872 ]]
[[0.28705558 0.7129444 ]]
[[0.30188313 0.69811684]]


Testing: 100%|██████████| 67/67 [00:07<00:00,  8.53it/s]
